<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>page d'accueil</title>
</head>
<body>
    	<header>
				<img src="" alt="logo">
				<nav>
					<ul>
						<li><a href=""></a>Qui est nous?</li>
						<li><a href=""></a>Notre plate</li>
						<li><a href=""></a>réserve</li>
						<li><a href=""></a>connexion</li>
					</ul>
				</nav>	
		</header>
			
		<main>
		    <h1>Porte de Damas </h1>
		    <article>
		    <p>Qui est nous?</p>
		    <p>Nous sommes une famille syrienne qui a décidé de vivre en France après plusieurs déménagements dus à la guerre en Syrie.
		    Nous avons décidé de démarrer notre projet en raison de notre passion pour la cuisine syrienne et la diversité de ses plats.</p>
		    <p>Dans la culture culinaire syrienne, nous n'avons pas l'entrée, le plat principal, etc.
		    Nous mettons tous les plats sur la table et chacun commence comme il préfère.</p>
		    </article>
		</main>	
		
		<footer>
			<div>
		    <h2>contact info</h2>
		    <p><img src="../assets/img/phone.png"> 0762240069 </p>
		    <p><img src="../assets/img/email.png"> porte-damas@gmail.com </p>
		    </div>
		    <div>
		    <h2>Adresse</h2>
		    <p><img src="../assets/img/adresse.png">15 square yves monnier 35200 Rennes</p>
		    </div>
		    <div>
		    <h2>heures d'ouvertures</h2>
		    <p>Du Mardi au Dimanche
		    	10:00 jusqu'à 22:00
		    	Le Lundi est fermée</p>
		    </div>
		</footer>
</body>
</html>