<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>page de connexion</title>
</head>
<body>
    	<header>
				<img src="" alt="logo">
				<nav>
					<ul>
						<li><a href=""></a>Qui est nous?</li>
						<li><a href=""></a>Notre plate</li>
						<li><a href=""></a>réserve</li>
						<li><a href=""></a>connexion</li>
					</ul>
				</nav>	
		</header>
			
		<main>
		    	<form action="" method="post">
        			<fieldset>
        				<legend>connexion</legend>
        				<div class="email">
        					<label for="email">Email</label><br>
        					<input type="email" id="email">
        				</div>
        				<div class="password">
        					<label for="password">Mot de passe</label><br>
        					<input type="password" id="password">
        				</div>
        			</fieldset>
            			<div>
            				<button type="submit" class="button">Se connecter</button>
            			</div>
	            </form>
		</main>	
		
		<footer>
			<div>
		    <h2>contact info</h2>
		    <p><img src="../assets/img/phone.png"> 0762240069 </p>
		    <p><img src="../assets/img/email.png"> porte-damas@gmail.com </p>
		    </div>
		    <div>
		    <h2>Adresse</h2>
		    <p><img src="../assets/img/adresse.png">15 square yves monnier 35200 Rennes</p>
		    </div>
		    <div>
		    <h2>heures d'ouvertures</h2>
		    <p>Du Mardi au Dimanche
		    	10:00 jusqu'à 22:00
		    	Le Lundi est fermée</p>
		    </div>
		</footer>
</body>
</html>