<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>page de connexion</title>
</head>
<body>
    	<header>
				<img src="" alt="logo">
				<nav>
					<ul>
						<li><a href=""></a>Qui est nous?</li>
						<li><a href=""></a>Notre plate</li>
						<li><a href=""></a>réserve</li>
						<li><a href=""></a>connexion</li>
					</ul>
				</nav>	
		</header>
			
		<main>
		    <section>
		        <h3>Plats végétariens</h3>
		        <article>
		            <h4></h4>
		            <img src="">
		            <p></p>
		        </article>
		    </section>
		    <section>
		        <h3>Plats de viande</h3>
		        <article>
		            <h4></h4>
		            <img src="">
		            <p></p>
		        </article>
		    </section>
		    <section>
		        <h3>Dessert</h3>
		        <article>
		            <h4></h4>
		            <img src="">
		            <p></p>
		        </article>
		    </section>
		</main>	
		
		<footer>
			<div>
		    <h2>contact info</h2>
		    <p><img src="../assets/img/phone.png"> 0762240069 </p>
		    <p><img src="../assets/img/email.png"> porte-damas@gmail.com </p>
		    </div>
		    <div>
		    <h2>Adresse</h2>
		    <p><img src="../assets/img/adresse.png">15 square yves monnier 35200 Rennes</p>
		    </div>
		    <div>
		    <h2>heures d'ouvertures</h2>
		    <p>Du Mardi au Dimanche
		    	10:00 jusqu'à 22:00
		    	Le Lundi est fermée</p>
		    </div>
		</footer>
</body>
</html>