<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>page de connexion</title>
</head>
<body>
    	<header>
				<img src="" alt="logo">
				<nav>
					<ul>
						<li><a href=""></a>Qui est nous?</li>
						<li><a href=""></a>Notre plate</li>
						<li><a href=""></a>réserve</li>
						<li><a href=""></a>connexion</li>
					</ul>
				</nav>	
		</header>
			
		<main>
		    	<form action="" method="post">
        			<fieldset>
        				<legend>réservez votre place</legend>
        				<div class="nom">
        					<label for="nom">Votre Nom et Prénom</label><br>
        					<input type="text" id="nom">
        				</div>
        				<div class="email">
        					<label for="email">Email</label><br>
        					<input type="email" id="email">
        				</div>
        				<div class="number">
        					<label for="number">Votre numéro</label><br>
        					<input type="number" id="number">
        				</div>
        				<div class="numPers">
        					<label for="numPers">Combien de personnes?</label><br>
        					<input type="number" id="numPers">
        				</div>
        				<div class="date">
        					<label for="date">Le Date</label><br>
        					<input type="date" id="date">
        				</div>
        				<div class="time">
        					<label for="time">L'heure</label><br>
        					<input type="time" id="time">
        				</div>
        				<div class="message">
        					<label for="message">Message</label><br>
        					<input type="text" id="message">
        				</div>
        			</fieldset>
            			<div>
            				<button type="submit" class="button">réserve</button>
            			</div>
	            </form>
		</main>	
		
		<footer>
			<div>
		    <h2>contact info</h2>
		    <p><img src="../assets/img/phone.png"> 0762240069 </p>
		    <p><img src="../assets/img/email.png"> porte-damas@gmail.com </p>
		    </div>
		    <div>
		    <h2>Adresse</h2>
		    <p><img src="../assets/img/adresse.png">15 square yves monnier 35200 Rennes</p>
		    </div>
		    <div>
		    <h2>heures d'ouvertures</h2>
		    <p>Du Mardi au Dimanche
		    	10:00 jusqu'à 22:00
		    	Le Lundi est fermée</p>
		    </div>
		</footer>
</body>
</html>